class_name SimulationEvent
extends RefCounted

enum Kind {
	COMMAND_ACCEPTED,
	COMMAND_REJECTED,
	UNIT_ARRIVED,
	UNIT_STUCK,
	ATTACK_STARTED,
	DAMAGE_APPLIED,
	UNIT_DESTROYED,
	TARGET_LOST,
	PROJECTILE_FIRED,
	PROJECTILE_IMPACTED,
	PROJECTILE_EXPIRED,
	ORE_DELIVERED,
	PRODUCTION_STARTED,
	UNIT_PRODUCED,
	FACTION_DEFEATED,
	FACTION_VICTORIOUS,
	TASK_STATE_CHANGED,
	UNIT_CONTROL_CHANGED,
	UNIT_REJOIN_STARTED,
	UNIT_REJOIN_COMPLETED,
	BUILDING_PLACED,
	CONSTRUCTION_COMPLETED,
	REPAIR_STARTED,
	BUILDING_REPAIRED,
	BUILDING_DESTROYED,
	HARVEST_CARGO_LOADED,
	ENEMY_PHASE_CHANGED,
	PRODUCTION_QUEUED,
	PRODUCTION_CANCELLED,
	RALLY_POINT_SET,
	UNIT_CARD_DEPLOYMENT_STARTED,
	UNIT_CARD_DEPLOYED,
	SUPPLY_CHANGED,
	REGION_CONTROL_CHANGED,
	REGION_SETTLED,
	SUPPORT_STARTED,
	SUPPORT_ENDED,
	ENEMY_REACTION_ARMED,
	ENEMY_REACTION_COMMITTED,
	UNIT_TERRAIN_CHANGED,
	SCOUT_CONTACT_REPORTED,
	UNIT_CARD_REINFORCED,
	ENGINEERING_ROUTE_OPENED,
	INTEL_CONTACT_EXPIRED,
	SUPPLY_NODE_ACTIVATED,
	UNIT_CARD_ORGANIZATION_CHANGED,
	UNIT_CARD_WITHDRAWN,
	DOCTRINE_EQUIPPED,
	REGION_CAPTURE_STARTED,
	REGION_CAPTURE_INTERRUPTED,
	BATTLE_CONCLUDED,
	TACTICAL_ACTION_STARTED,
	TACTICAL_ACTION_COMPLETED,
	TACTICAL_ACTION_INTERRUPTED,
	TACTICAL_IDENTIFIED,
	AMMUNITION_RESTORED,
	SUPPRESSION_APPLIED,
	STAFF_PLAN_DECIDED,
	COMMANDER_GRAPH_CHANGED,
}

var tick: int
var kind: Kind
var entity_id: int
var detail: String
# Finalized by the organization system before this tick is published.
var applied_amount: float = 0.0


func _init(new_tick: int, new_kind: Kind, new_entity_id: int, new_detail: String = "") -> void:
	tick = new_tick
	kind = new_kind
	entity_id = new_entity_id
	detail = new_detail
